[package]
name = "ignoring_parts_of_a_value_with_a_nested_"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
